# Generated by Django 5.2.4 on 2026-01-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=50)),
                ('important', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
